//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrashVanish {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrashVanish.lang_ru", typeof(lang_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Программа загружена.
        /// </summary>
        internal static string AppIsLoaded {
            get {
                return ResourceManager.GetString("AppIsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задачи с наборами, чувствительными к регистру, с комплексными правилами завершены.
        /// </summary>
        internal static string caseSensetiveSetsWithCmplxRulesAreDone {
            get {
                return ResourceManager.GetString("caseSensetiveSetsWithCmplxRulesAreDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задачи, чувствительные к регистру, с комплексными правилами завершены.
        /// </summary>
        internal static string caseSensetiveTasksWithCmplxRulesAreDone {
            get {
                return ResourceManager.GetString("caseSensetiveTasksWithCmplxRulesAreDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задачи с комплексными правилами завершены.
        /// </summary>
        internal static string complexRulesAreDone {
            get {
                return ResourceManager.GetString("complexRulesAreDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задачи с наборами, с комплексными правилами, завершены.
        /// </summary>
        internal static string complexSetsAreDone {
            get {
                return ResourceManager.GetString("complexSetsAreDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расширение не корректно.
        /// </summary>
        internal static string extIsInvalid {
            get {
                return ResourceManager.GetString("extIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл &quot;{0}&quot; уже существует в {1}, пропускаю....
        /// </summary>
        internal static string fileAlreadyExist {
            get {
                return ResourceManager.GetString("fileAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет файлов для задачи &quot;{0}&quot;, иду дальше.
        /// </summary>
        internal static string noFilesForExt {
            get {
                return ResourceManager.GetString("noFilesForExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет файлов для задачи &quot;{0}&quot; + &quot;{1}&quot;, иду дальше.
        /// </summary>
        internal static string noFilesForExtAndInclude {
            get {
                return ResourceManager.GetString("noFilesForExtAndInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не все файлы &quot;{0}&quot; были скопированы успешно.
        /// </summary>
        internal static string notAllFilesWithExtWereMoved {
            get {
                return ResourceManager.GetString("notAllFilesWithExtWereMoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Путь не корректен.
        /// </summary>
        internal static string pathIsInvalid {
            get {
                return ResourceManager.GetString("pathIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Относительные пути запрещены.
        /// </summary>
        internal static string relPathesAreForbidden {
            get {
                return ResourceManager.GetString("relPathesAreForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обязательные поля не заполнены.
        /// </summary>
        internal static string ReqFieldsAreEmpty {
            get {
                return ResourceManager.GetString("ReqFieldsAreEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правило для {0} создано.
        /// </summary>
        internal static string ruleCreatedSuccessfuly {
            get {
                return ResourceManager.GetString("ruleCreatedSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правило для {0} уже существует.
        /// </summary>
        internal static string ruleForExtAlreadyExist {
            get {
                return ResourceManager.GetString("ruleForExtAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задачи с правилами завершены.
        /// </summary>
        internal static string rulesAreDone {
            get {
                return ResourceManager.GetString("rulesAreDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правило для {0} обновлено.
        /// </summary>
        internal static string ruleUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("ruleUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Набор успешно добавлен.
        /// </summary>
        internal static string setAddedSuccessfully {
            get {
                return ResourceManager.GetString("setAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задачи с наборами завершены.
        /// </summary>
        internal static string setsAreDone {
            get {
                return ResourceManager.GetString("setsAreDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старт.
        /// </summary>
        internal static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задача для &quot;{0}&quot; завершилась успешно. Перемещенно файлов: {1}.
        /// </summary>
        internal static string taskCompleted {
            get {
                return ResourceManager.GetString("taskCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задача для &quot;0&quot; + &quot;1&quot; завершилось успешно. Перемещенно файлов: {2}.
        /// </summary>
        internal static string taskCompletedWithIncludes {
            get {
                return ResourceManager.GetString("taskCompletedWithIncludes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все задачи завершены за {0} миллисекунд.
        /// </summary>
        internal static string tasksAreDoneForElapsedTime {
            get {
                return ResourceManager.GetString("tasksAreDoneForElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. Чтобы скопировать файл в {1} запустите программу от имени администратра.
        /// </summary>
        internal static string unauthorizedAccessExceptionMessage {
            get {
                return ResourceManager.GetString("unauthorizedAccessExceptionMessage", resourceCulture);
            }
        }
    }
}
